pipeline {
    agent any

    stages {
        stage('Checkout SCM stage') {
            steps {
                // Checkout SCM stage
                script {
                    checkout scm   
                }
            }
        }
        stage('Install Terraform') {
            steps {
                // Install Terraform dynamically during the pipeline execution
                sh '''
                    # Add the HashiCorp GPG key
                    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

                    # Add the official HashiCorp Linux repository
                    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

                    # Update and install Terraform
                    sudo apt-get update && sudo apt-get install -y terraform

                    # Verify installation
                    terraform -v
                '''
            }
        }
        
        stage('Initialize Terraform') {
            steps {
                dir('Terraform') {
                    withCredentials([aws(credentialsId: 'aws-jenkins-credentials')]) {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        failure {
            echo "Terraform infrastructure setup failed."
            cleanWs()
        }
    }
}
