pipeline {
    agent any

    stages {
        stage('Checkout SCM stage') {
            steps {
                // Checkout SCM stage
                script {
                    checkout scm   
                }
            }
        }
        stage('Install Terraform') {
            steps {
                // Install Terraform in the current workspace without sudo
                sh '''
                    # Download Terraform binary
                    curl -O https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip

                    # Unzip and move Terraform to the local bin
                    unzip terraform_1.5.6_linux_amd64.zip
                    chmod +x terraform

                    # Move Terraform to a known directory (workspace) and add it to PATH
                    mv terraform /var/jenkins_home/workspace/Final\\ Project/bin/

                    # Add Terraform binary path to the environment variable PATH
                    export PATH=$PATH:/var/jenkins_home/workspace/Final\\ Project/bin

                    # Check Terraform version to confirm installation
                    terraform -v
                '''
            }
        }
        
        stage('Initialize Terraform') {
            steps {
                dir('Terraform') {
                    withCredentials([aws(credentialsId: 'aws-jenkins-credentials')]) {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        failure {
            echo "Terraform infrastructure setup failed."
            cleanWs()
        }
    }
}
